apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otelcolcontrib-binding
  labels:
    app: otel-collector
subjects:
- kind: ServiceAccount
  name: otel-collector-serviceaccount
  namespace: default
roleRef:
  kind: ClusterRole
  name: otel-collector-clusterrole
  apiGroup: rbac.authorization.k8s.io