apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    app: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      serviceAccountName: otel-collector-serviceaccount
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.101.0
          args: ["--config", "/etc/config/config.yaml"]
          volumeMounts:
            - name: config
              mountPath: /etc/config
            - name: varlogpods
              mountPath: /var/log/pods
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true


          imagePullPolicy: IfNotPresent
          env: 
            - name: DASH0_AUTHORIZATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dash0-secrets
                  key: dash0-authorization-token
      volumes:
        - name: config
          configMap:
            name: otel-collector-cofigmap
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers