apiVersion: v1
kind: Service
metadata:
  name: otel-collector-service
spec:
  clusterIP: None
  ports:
  - name: grpc-otlp
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: http-otlp
    port: 4318
    protocol: TCP
    targetPort: 4318
  selector:
    app: otel-collector
  