apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: otel-instrumentation
spec:
  exporter:
    endpoint: http://opentelemetry-collector.opentelemetry:4317
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: always_on
    argument: "1"