service:
    log_level: debug
    Daemon: Off
    Flush: 1
    HTTP_Server: On
    HTTP_Listen: 0.0.0.0
    HTTP_Port: 2020
    Health_Check: On
    # Parsers_File: /fluent-bit/etc/parsers.conf


pipeline:
  inputs:
    - name: tail
      Path: /var/log/containers/*.log
      # Path_Key: filepath
      multiline.parser: docker, cri
      Tag: kube.*
      Mem_Buf_Limit: 5MB      
      Skip_Long_Lines: On      
      # processors:
      #   logs:          
      #     - name: opentelemetry_envelope
          # - name: content_modifier
          #   context: otel_resource_attributes
          #   action: upsert
          #   key: "k8s.pod.id"
          #   value: filepath

          # - name: content_modifier
          #   context: otel_resource_attributes
          #   action: upsert
          #   key: "k8s.pod.id"
          #   value: "tmp"
            # add: filepath ${filepath}

  filters:    
    - name: kubernetes
      match: kube.*
      merge_log: on
      keep_log: off
      processors:
        logs:          
          - name: opentelemetry_envelope

      
  outputs:
    - name: opentelemetry
      match: '*'
      host: ingress.eu-west-1.aws.dash0.com
      port: 443
      header: Authorization Bearer ${DASH0_AUTHORIZATION_TOKEN}
      metrics_uri: /v1/metrics
      Logs_uri: /v1/logs
      Traces_uri: /v1/traces
      Tls:  On
      # logs_body_key: body
      # logs_span_id_message_key: span_id
      # logs_trace_id_message_key: trace_id
      # logs_severity_text_message_key: loglevel
      # logs_severity_number_message_key: lognum
      
    