service:
    log_level: info
    Daemon: Off
    Flush: 1
    HTTP_Server: On
    HTTP_Listen: 0.0.0.0
    HTTP_Port: 2020
    Health_Check: On
    Parsers_File: "/fluent-bit/etc/conf/custom_parsers.conf"

pipeline:
  inputs:
    - name: tail
      Path: /var/log/containers/*.log
      multiline.parser: docker, cri
      Tag: kube.*
      Mem_Buf_Limit: 5MB      
      Skip_Long_Lines: On  
  
  filters:
    - name: kubernetes
      match: kube.*
      merge_log: on
      keep_log: off
   
  outputs:
    - name: opentelemetry
      match: 'kube.*'
      host: ingress.eu-west-1.aws.dash0.com
      port: 443
      header: Authorization Bearer ${DASH0_AUTHORIZATION_TOKEN}
      metrics_uri: /v1/metrics
      Logs_uri: /v1/logs
      Traces_uri: /v1/traces
      Tls:  On      