env:
  - name: DASH0_AUTHORIZATION_TOKEN
    valueFrom:
      secretKeyRef:
        name: dash0-secrets
        key: dash0-authorization-token

service:
    flush: 1
    log_level: info

pipeline:
  inputs:
        - name: random
          tag: test
          samples: 10
          
  filters:
    - name: kubernetes
      match: "*"
      Merge_Log: On
      Keep_Log: Off
      K8S-Logging.Parser: On
      K8S-Logging.Exclude: On

  outputs: 
    - name: opentelementry        
      Match: "*"
      Host: ingress.eu-west-1.aws.dash0.com
      Port: 443    
      Header: Authorization Bearer ${DASH0_AUTHORIZATION_TOKEN}
      Metrics_uri: /v1/metrics
      Logs_uri: /v1/logs
      Traces_uri: /v1/traces
      Tls:  On
      logs_body_key: message
      logs_span_id_message_key: span_id
      logs_trace_id_message_key: trace_id
      logs_severity_text_message_key: loglevel
      logs_severity_number_message_key: lognum