env:
  - name: DASH0_AUTHORIZATION_TOKEN
    valueFrom:
      secretKeyRef:
        name: dash0-secrets
        key: dash0-authorization-token

config:

  filters: |
      [FILTER]
          Name kubernetes
          Match kube.*
          Merge_Log On
          Keep_Log Off
          K8S-Logging.Parser On
          K8S-Logging.Exclude On

      [FILTER]
          Name nest
          Match kube.*
          Operation lift
          Nested_under  kubernetes
          add_prefix kubernetes_

      [FILTER]
          Name nest
          Match kube.*
          Operation lift
          Nested_under  kubernetes_labels

      # [FILTER]
      #     Name nest
      #     Match kube.*
      #     Operation lift
      #     Wildcard k8s.*

      [FILTER]
          Name modify
          Match kube.*
          Rename log content
          Rename kubernetes_pod_id k8s.pod.id
          Rename kubernetes_pod_name k8s.pod.name
          Rename kubernetes_namespace_name k8s.namespace.name
          Rename kubernetes_container_name k8s.container.name
          
  
  outputs: |
    [OUTPUT]
        Name opentelemetry
        Match *
        Host ingress.eu-west-1.aws.dash0.com
        Port 443    
        Header Authorization Bearer ${DASH0_AUTHORIZATION_TOKEN}
        Metrics_uri /v1/metrics
        Logs_uri /v1/logs
        Traces_uri /v1/traces
        Tls  On
        logs_body_key message
        logs_span_id_message_key span_id
        logs_trace_id_message_key trace_id
        logs_severity_text_message_key loglevel
        logs_severity_number_message_key lognum