connectors:
  spanmetrics: {}
exporters:
  otlp/dash0:
    auth:
      authenticator: bearertokenauth/dash0
    endpoint: ingress.eu-west-1.aws.dash0.com:4317
  debug: {}
  opensearch:
    http:
      endpoint: http://otel-demo-opensearch:9200
      tls:
        insecure: true
    logs_index: otel
  otlp:
    endpoint: 'opentelemetry-demo-jaeger-collector:4317'
    tls:
      insecure: true
  otlphttp/prometheus:
    endpoint: http://opentelemetry-demo-prometheus-server:9090/api/v1/otlp
    tls:
      insecure: true
extensions:
  bearertokenauth/dash0:
    scheme: Bearer
    token: ${env:DASH0_AUTHORIZATION_TOKEN}
  health_check:
    endpoint: ${env:MY_POD_IP}:13133
processors:
  batch: {}
  k8sattributes:
    extract:
      metadata:
      - k8s.namespace.name
      - k8s.deployment.name
      - k8s.statefulset.name
      - k8s.daemonset.name
      - k8s.cronjob.name
      - k8s.job.name
      - k8s.node.name
      - k8s.pod.name
      - k8s.pod.uid
      - k8s.pod.start_time
    passthrough: false
    pod_association:
    - sources:
      - from: resource_attribute
        name: k8s.pod.ip
    - sources:
      - from: resource_attribute
        name: k8s.pod.uid
    - sources:
      - from: connection
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
  resource:
    attributes:
    - action: insert
      from_attribute: k8s.pod.uid
      key: service.instance.id
receivers:
  jaeger:
    protocols:
      grpc:
        endpoint: ${env:MY_POD_IP}:14250
      thrift_compact:
        endpoint: ${env:MY_POD_IP}:6831
      thrift_http:
        endpoint: ${env:MY_POD_IP}:14268
  otlp:
    protocols:
      grpc:
        endpoint: ${env:MY_POD_IP}:4317
      http:
        cors:
          allowed_origins:
          - http://*
          - https://*
        endpoint: ${env:MY_POD_IP}:4318
  prometheus:
    config:
      scrape_configs:
      - job_name: opentelemetry-collector
        scrape_interval: 10s
        static_configs:
        - targets:
          - ${env:MY_POD_IP}:8888
  zipkin:
    endpoint: ${env:MY_POD_IP}:9411
service:
  extensions:
  - health_check
  - bearertokenauth/dash0
  pipelines:
    logs:
      exporters:
      - opensearch
      - debug
      - otlp/dash0
      processors:
      - k8sattributes
      - memory_limiter
      - resource
      - batch
      receivers:
      - otlp
    metrics:
      exporters:
      - otlphttp/prometheus
      - debug
      - otlp/dash0
      processors:
      - k8sattributes
      - memory_limiter
      - resource
      - batch
      receivers:
      - otlp
      - spanmetrics
    traces:
      exporters:
      - otlp
      - debug
      - spanmetrics
      - otlp/dash0
      processors:
      - k8sattributes
      - memory_limiter
      - resource
      - batch
      receivers:
      - otlp
      - jaeger
      - zipkin
  telemetry:
    metrics:
      address: ${env:MY_POD_IP}:8888
