opentelemetry-collector:
  config:
    exporters:
      otlp/dash0:
        auth:
          authenticator: bearertokenauth/dash0
        endpoint: ingress.eu-west-1.aws.dash0.com:4317
    extensions:
      bearertokenauth/dash0:
        scheme: Bearer
        token: ${env:DASH0_AUTHORIZATION_TOKEN}
    service:
      extensions:
        - bearertokenauth/dash0
        - health_check
        
      pipelines:
        traces:
          exporters: [otlp/dash0,spanmetrics]
        logs:
          exporters: [otlp/dash0]
        metrics:
          exporters: [otlp/dash0]
  extraEnvs:
  - name: DASH0_AUTHORIZATION_TOKEN
    valueFrom:
      secretKeyRef:
        name: dash0-secrets
        key: dash0-authorization-token

