apiVersion: apps/v1
kind: Deployment
metadata:
  name: callerapp
  labels:
    app: callerapp
spec:
  selector:
    matchLabels:
      app: callerapp
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: callerapp
    spec:
      containers:
      - name: callerapp
        image: ghcr.io/pjuentgen/callerapp:latest
        imagePullPolicy: Always
        env:           
          - name: OTEL_LOG_LEVEL
            value: "info"
          - name: URLS
            value: "http://node-demoapp-service.default:8080"
          - name: INTERVAL
            value: "1000"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"             