---
apiVersion: v1
kind: Service
metadata:
  name: node-demoapp-service
spec:
  type: ClusterIP
  selector:
    app: node-demoapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      