apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-demoapp
  labels:
    app: node-demoapp
spec:
  selector:
    matchLabels:
      app: node-demoapp
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: node-demoapp
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "true"        
    spec:
      containers:
      - name: node-demoapp
        image: ghcr.io/pjuentgen/node-demoapp:latest
        imagePullPolicy: Always
        env:           
          - name: OTEL_LOG_LEVEL
            value: "info"
          - name: PORT
            value: "8080"
          - name: TIME
            value: "500"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3          
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m" 