apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: opentelemetry
spec:
  mode: daemonset
  volumeMounts:
    - name: varlogpods
      mountPath: /var/log/pods
      readOnly: true
    - name: varlibdockercontainers
      mountPath: /var/lib/docker/containers
      readOnly: true
  volumes:
    - name: varlogpods
      hostPath:
        path: /var/log/pods
    - name: varlibdockercontainers
      hostPath:
        path: /var/lib/docker/containers
  env:
    - name: DASH0_AUTHORIZATION_TOKEN
      valueFrom:
        secretKeyRef:
          name: dash0-secrets
          key: dash0-authorization-token
  config:
    exporters:
      otlp/dash0:
        auth:
          authenticator: bearertokenauth/dash0
        endpoint: ingress.eu-west-1.aws.dash0.com:4317
    extensions:
      bearertokenauth/dash0:
        scheme: Bearer
        token: ${env:DASH0_AUTHORIZATION_TOKEN}
      health_check: {}
    processors:
      batch: {}
      memory_limiter:
        check_interval: 1s
        limit_percentage: 50
        spike_limit_percentage: 30
    receivers:
      prometheus:
        config:
          scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 30s
            static_configs:
            - targets: [ '0.0.0.0:8888' ]
      otlp:
        protocols: 
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    service:
      extensions:
        - bearertokenauth/dash0
        - health_check
      pipelines:
        logs:
          exporters:
            - otlp/dash0
          processors:
            - batch                    
          receivers:
            - otlp
        metrics:
          exporters:
            - otlp/dash0
          processors:
            - batch
          receivers:
            - otlp
            - prometheus
        traces:
          exporters:
            - otlp/dash0
          processors:
            - batch
          receivers:
            - otlp
      telemetry:
        metrics:
          address: 0.0.0.0:8888
